### ISSUE TITLE
运行feature_extract.py时抛出forward() got an unexpected keyword argument 'feature_layer'

### ISSUE THREAD

**Issue by rui-ao** [wanboyang/anomly_feature.pytorch#3]
作者好，已经修改了必要的参数，仍然出现上述问题，暂未找到解决思路，怀疑是之前生成的帧列表可能出现问题，尤其是label这个列表有几分不明白，能否提供这些text的示例文件。下图是我运行时的结果，ubuntu下运行也是类似结果
![_20210217050243](https://user-images.githubusercontent.com/46027934/115107663-fb052680-9f9e-11eb-8ccb-daa5831dd673.png)
![_20210317050308](https://user-images.githubusercontent.com/46027934/115107668-00fb0780-9f9f-11eb-9493-fec2df64c5aa.png)
![_20210317050322](https://user-images.githubusercontent.com/46027934/115107677-05bfbb80-9f9f-11eb-9462-779a84c51ede.png)

**Comment by wanboyang** [comment]
在使用默认参数时,是否可以成功提取特征?

**Comment by Yii-maker** [comment]
@chiao666   我也遇到了这个问题，请问您解决了吗？
