### ISSUE TITLE
shanghaiTech Dataset

### ISSUE THREAD

**Issue by quanoo** [wanboyang/anomly_feature.pytorch#4]
Hello, do you have a download link to ShanghaiTech anomaly detection data set, I haven't found it, thank you

**Comment by quanoo** [comment]
https://svip-lab.github.io/dataset/campus_dataset.html    The connection here is broken

**Comment by wanboyang** [comment]
The shanghaitech dataset can be downloaded as follow:
link: https://pan.baidu.com/s/14FvnWUchazOLla7YeFEEcQ 
code: 6g4m

**Comment by wanboyang** [comment]
The shanghaitech dataset can be downloaded as follow:
link: https://pan.baidu.com/s/14FvnWUchazOLla7YeFEEcQ 
code: 6g4m

**Comment by wanboyang** [comment]
The shanghaitech dataset can be downloaded as follow:
link: https://pan.baidu.com/s/14FvnWUchazOLla7YeFEEcQ 
code: 6g4m
