### ISSUE TITLE
'feature_layer' in feature_extract.py

### ISSUE THREAD

**Issue by Yii-maker** [wanboyang/anomly_feature.pytorch#5]
Thank you very much for your work.
 In document feature_extract.py, How do we determine 'feature_layer '(e.g., line 39)  in terms of  'fc_layer' ?

**Comment by chiao666** [comment]
Hello, have you successfully run out of this code? Can you give me a more detailed description or guidance? Thank you very much!

**Comment by wanboyang** [comment]
you can  use the parameter   "--fc-layer" in https://github.com/wanboyang/anomly_feature.pytorch/blob/59a1e757d5514f89ebea50c1b4c79f732ebeebc1/feature_extract.py#L113
