### ISSUE TITLE
Where is the models.py file?

### ISSUE THREAD

**Issue by abhishekaich27** [wanboyang/anomly_feature.pytorch#6]
Hi,

Can you please provide the pretrained model on Google Drive/one Drive/ Drop Box? Also, I couldn't find the model.py file in the repo. Can you point that out?

**Comment by wanboyang** [comment]
Download the model.zip in (link: https://pan.baidu.com/s/1g4XGLqRoRJhQwIGtHif2jg password: dzqm), and unpress it to the root.

**Comment by abhishekaich27** [comment]
Thanks for the response. Can you please upload it to Google Drive? It cannot be accessed from my location.

Also, can you point to the `model.py` file?

**Comment by wanboyang** [comment]
link:https://stujxufeeducn-my.sharepoint.com/:u:/g/personal/2201810057_stu_jxufe_edu_cn/ES03rInofulLq9ZY7GICHrMBIDdKDx2siAZ-x3Qgp7T0ow?e=ugVZCC
pw:1234
The model.zip contains the model.py.
