### ISSUE TITLE
I3D rgb and optical flow festures of UCF-crime

### ISSUE THREAD

**Issue by Yii-maker** [wanboyang/anomly_feature.pytorch#7]
Does anyone have the I3D rgb and optical flow festures of UCF-crime?

**Comment by wanboyang** [comment]
You can download the I3D rgb and optical flow festures of UCF-crime in project `https://github.com/wanboyang/anomaly_detection_LAD2000`
For Auenve, ped2, shanghaitech and UCF_Crime, we provide the i3d features in (link: https://pan.baidu.com/s/1fYAlFoTdcg8BgRdqoLQ2Bg pw: njy2) or (link:https://stujxufeeducn-my.sharepoint.com/:f:/g/personal/2201810057_stu_jxufe_edu_cn/EuQvbLCDoIxLgmcgpJRqcbIBzJSc7D6V-q151gLsWyFTrQ?e=JNbUEc pw:123456)
