### ISSUE TITLE
feature_extract.py

### ISSUE THREAD

**Issue by fmandune** [wanboyang/anomly_feature.pytorch#8]
![QQ图片20211008185736](https://user-images.githubusercontent.com/92158184/136545518-e0185770-6cf9-42da-8f25-617c7667d867.png)
后面俩个文件是如何获得的

**Comment by wanboyang** [comment]
函数 https://github.com/wanboyang/anomly_feature.pytorch/blob/59a1e757d5514f89ebea50c1b4c79f732ebeebc1/feature_extract.py#L125
可以生成
